"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class msg_r(object):
    __slots__ = ["knee_position_actual", "ankle_position_actual", "knee_velocity_actual", "ankle_velocity_actual", "knee_torque_actual", "ankle_torque_actual", "Error_Code", "knee_temperature", "ankle_temperature"]

    __typenames__ = ["float", "float", "float", "float", "float", "float", "byte", "float", "float"]

    __dimensions__ = [None, None, None, None, None, None, None, None, None]

    def __init__(self):
        self.knee_position_actual = 0.0
        self.ankle_position_actual = 0.0
        self.knee_velocity_actual = 0.0
        self.ankle_velocity_actual = 0.0
        self.knee_torque_actual = 0.0
        self.ankle_torque_actual = 0.0
        self.Error_Code = 0
        self.knee_temperature = 0.0
        self.ankle_temperature = 0.0

    def encode(self):
        buf = BytesIO()
        buf.write(msg_r._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">ffffffBff", self.knee_position_actual, self.ankle_position_actual, self.knee_velocity_actual, self.ankle_velocity_actual, self.knee_torque_actual, self.ankle_torque_actual, self.Error_Code, self.knee_temperature, self.ankle_temperature))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != msg_r._get_packed_fingerprint():
            raise ValueError("Decode error")
        return msg_r._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = msg_r()
        self.knee_position_actual, self.ankle_position_actual, self.knee_velocity_actual, self.ankle_velocity_actual, self.knee_torque_actual, self.ankle_torque_actual, self.Error_Code, self.knee_temperature, self.ankle_temperature = struct.unpack(">ffffffBff", buf.read(33))
        return self
    _decode_one = staticmethod(_decode_one)

    def _get_hash_recursive(parents):
        if msg_r in parents: return 0
        tmphash = (0xb23e13f5bc30ce24) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if msg_r._packed_fingerprint is None:
            msg_r._packed_fingerprint = struct.pack(">Q", msg_r._get_hash_recursive([]))
        return msg_r._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", msg_r._get_packed_fingerprint())[0]

