// Generated by gencpp from file ros_ctrl/Kill.msg
// DO NOT EDIT!


#ifndef ROS_CTRL_MESSAGE_KILL_H
#define ROS_CTRL_MESSAGE_KILL_H

#include <ros/service_traits.h>


#include <ros_ctrl/KillRequest.h>
#include <ros_ctrl/KillResponse.h>


namespace ros_ctrl
{

struct Kill
{

typedef KillRequest Request;
typedef KillResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Kill
} // namespace ros_ctrl


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ros_ctrl::Kill > {
  static const char* value()
  {
    return "c1f3d28f1b044c871e6eff2e9fc3c667";
  }

  static const char* value(const ::ros_ctrl::Kill&) { return value(); }
};

template<>
struct DataType< ::ros_ctrl::Kill > {
  static const char* value()
  {
    return "ros_ctrl/Kill";
  }

  static const char* value(const ::ros_ctrl::Kill&) { return value(); }
};


// service_traits::MD5Sum< ::ros_ctrl::KillRequest> should match
// service_traits::MD5Sum< ::ros_ctrl::Kill >
template<>
struct MD5Sum< ::ros_ctrl::KillRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ros_ctrl::Kill >::value();
  }
  static const char* value(const ::ros_ctrl::KillRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_ctrl::KillRequest> should match
// service_traits::DataType< ::ros_ctrl::Kill >
template<>
struct DataType< ::ros_ctrl::KillRequest>
{
  static const char* value()
  {
    return DataType< ::ros_ctrl::Kill >::value();
  }
  static const char* value(const ::ros_ctrl::KillRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ros_ctrl::KillResponse> should match
// service_traits::MD5Sum< ::ros_ctrl::Kill >
template<>
struct MD5Sum< ::ros_ctrl::KillResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ros_ctrl::Kill >::value();
  }
  static const char* value(const ::ros_ctrl::KillResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_ctrl::KillResponse> should match
// service_traits::DataType< ::ros_ctrl::Kill >
template<>
struct DataType< ::ros_ctrl::KillResponse>
{
  static const char* value()
  {
    return DataType< ::ros_ctrl::Kill >::value();
  }
  static const char* value(const ::ros_ctrl::KillResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROS_CTRL_MESSAGE_KILL_H
